<?php
/**
*
* CSS Flip
*
* @license   LGPL (http://www.gnu.org/licenses/gpl.html)
* @url			 http://www.github.com/parmaja/cssflip
* @author    Zaher Dirkey <zaher at parmaja dot com>
*
*/
?>
<?
  header("Content-Type: text/css");
  include 'cf_classes.php';
?>
/** Auto generated by cssFlip.php */
<?
  css_switch_file('D:\work\php\cssFlip\test.css');
?>